### ISSUE TITLE
demo needs user and pw

### ISSUE THREAD

**Issue by hpvd** [FalkorDB/falkordb-browser#100]
was very curious :-)
but demo advertised in readme seems to need a user and pw...

https://browser.falkordb.com/

![2024-02-19_18h21_20](https://github.com/FalkorDB/falkordb-browser/assets/5681880/2273f7d2-4117-4897-87d2-c66b6b8f30cd)

**Comment by gkorland** [comment]
username and password are optional depending how you started the server

**Comment by hpvd** [comment]
hmm seems not to be optional:
![2024-02-21_12h58_18](https://github.com/FalkorDB/falkordb-browser/assets/5681880/e6df434f-7e8f-4042-9daa-42b6aeae5a79)

**Comment by gkorland** [comment]
the server host is not optional :) you need to set your endpoint

**Comment by hpvd** [comment]
aaah ok now I get it :-)
was expecting a full Demo on your site (incl Server and demo data)...

**Comment by gkorland** [comment]
you're right, we'll get it connected.
Meanwhile if you want to create a demo free sandbox database you can use https://cloud.falkordb.com/
