### ISSUE TITLE
Build a login page to replace the default login page 

### ISSUE THREAD

**Issue by gkorland** [FalkorDB/falkordb-browser#35]
Should look pretty similar to the current login page, but not as a stand alone page but as an integrated page in the main page.
![image](https://github.com/FalkorDB/falkordb-browser/assets/753206/670e69d6-e14a-4a9d-b1e2-7fdfa2407131)

**Comment by Full-stack-Web-Dev-BD** [comment]
Can you please  explain this issue  , by adding some  details  please ?

**Comment by gkorland** [comment]
Currently when you click on `connect` we show a full login page.
![image](https://github.com/FalkorDB/falkordb-browser/assets/753206/542de87a-4438-4af7-b206-8dae188fed1a)

But we would like it to be a child page like this:

![image](https://github.com/FalkorDB/falkordb-browser/assets/753206/c7d3f42d-c99c-40df-b397-fc1a542630dd)
