### ISSUE TITLE
CMD_INFO role in DB config

### ISSUE THREAD

**Issue by Naseem77** [FalkorDB/falkordb-browser#406]
A bug occurs when attempting to change the CMD_Info field in the settings. According to the CMD_Info documentation, the valid values for this field are yes and no (representing "on" and "off"). However, an error is triggered when trying to update the field to these valid values, or even when attempting to set it to its current value (e.g., 1). This issue is reproducible through both the API and UI on the staging repository.

- Steps to Reproduce:

Navigate to the settings page.
Attempt to update the CMD_Info field to a new number or yes/no value.
Try changing the field to its current value (e.g., 1).
Observe the error message.

![Image](https://github.com/user-attachments/assets/558e5859-11f4-4b2e-bfe7-e54c5d088362)

![Image](https://github.com/user-attachments/assets/9c3bab7b-2b5b-4fcc-a3ad-775fe8c8349d)

**Comment by Anchel123** [comment]
you just need to give yes / no in number 
so yes is 1 and no is 0

**Comment by Naseem77** [comment]
Indeed, attempting to change the value to 0 or 1 from the current value results in error.

![00](https://github.com/user-attachments/assets/52ff36f0-603d-43ab-ad42-23cb8727f4dc)
