### ISSUE TITLE
replace signin/sighout with connect/disconnect

### ISSUE THREAD

**Issue by gkorland** [FalkorDB/falkordb-browser#47]
![image](https://github.com/FalkorDB/falkordb-browser/assets/753206/1a30977e-b487-4e0c-8868-7ed15862d77f)
![image](https://github.com/FalkorDB/falkordb-browser/assets/753206/3df66ce4-3b56-4cc5-a6c7-4d37e7f477ce)

**Comment by gkorland** [comment]
ref #35

**Comment by Full-stack-Web-Dev-BD** [comment]
Hi , I gone through , as in this issue, we are  just changing the  text of  those Button  , As like 

From : ![image](https://github.com/FalkorDB/falkordb-browser/assets/60449971/18436a2c-044b-44e5-bf17-cbe8e3946381)
Done as : 
![image](https://github.com/FalkorDB/falkordb-browser/assets/60449971/3aea9504-d791-429c-bbb7-c6ce681ed570)


From :
![image](https://github.com/FalkorDB/falkordb-browser/assets/60449971/2b8089cf-af1d-41ef-b0e7-5fbde3d527c6)

Done as : 
![image](https://github.com/FalkorDB/falkordb-browser/assets/60449971/43d4a875-4bd3-4aff-9528-93210c9bf677)





Note : There is not feature  improvement or Update , its  just Text update !
