### ISSUE TITLE
Show available graphs in a drop-down list in Graph view

### ISSUE THREAD

**Issue by gkorland** [FalkorDB/falkordb-browser#50]
![image](https://github.com/FalkorDB/falkordb-browser/assets/753206/d0bfff23-eb76-4c5d-a24f-70caa064e98e)

Should use a combobox with input

![image](https://github.com/FalkorDB/falkordb-browser/assets/753206/5e8999d5-f7a2-4776-bbf5-b497b2f783ce)

FalkorDB provides a `GRAPH.LIST` command that returns the list of available graphs

**Comment by Full-stack-Web-Dev-BD** [comment]
Hi , 

I did checked that our  Graph loading from API call 
`        let result = await fetch(`/api/graph?graph=${prepareArg(state.graphName)}&query=${prepareArg(q)}`, {
            method: 'GET',
            headers: {
                'Content-Type': 'application/json'
            }
        })
`
But  while i dive into the  data , i did not finded any List  element as you mentioned on this issue 
=>"FalkorDB provides a GRAPH.LIST command that returns the list of available graphs"

Here is the SS 
![image](https://github.com/FalkorDB/falkordb-browser/assets/60449971/71ce737f-1c1d-4991-bace-a2f8d38047fd)

**Comment by Full-stack-Web-Dev-BD** [comment]
While i tried with a graph name (pallets-flask) its not loading its  propertise  , it just  loading a empty screen , 
 Graph:
![image](https://github.com/FalkorDB/falkordb-browser/assets/60449971/7774db2f-563d-483e-97fb-9b76c253bea7)
List:
![image](https://github.com/FalkorDB/falkordb-browser/assets/60449971/ca3b63c1-2a22-454a-b9a7-e1d8135f9cc4)
