### ISSUE TITLE
Add syntax highlighting to query box

### ISSUE THREAD

**Issue by swilly22** [FalkorDB/falkordb-browser#56]
The Query box should be grammar aware,
Similar to IDEs where the text is colored according to the language concepts, the input text within our query box should be "Cypher aware" colored accordingly.

**Comment by gkorland** [comment]
@swilly22 can you extend? what do you expect here?

**Comment by swilly22** [comment]
> @swilly22 can you extend? what do you expect here?

I've updated the issue description
