### ISSUE TITLE
Unable to login if port other than 3000 is used

### ISSUE THREAD

**Issue by schwab** [FalkorDB/falkordb-browser#62]
In my environment, I have other services on the default port of 3000, so when next starts up it automatcially finds an available port of 3002:
```
> next dev

 ⚠ Port 3000 is in use, trying 3001 instead.
 ⚠ Port 3001 is in use, trying 3002 instead.
   ▲ Next.js 14.1.0
   - Local:        http://localhost:3002
   - Environments: .env
```
This appears to work and the falkordb-browser comes up with a login prompt. However, when you attempt to login, it redirects back to port 3000 instead of the actual port of 3002.  This makes it impossible to continue to a logged in environment. The Login page will need to detect the port that the site is currently working on and redirect to the correct port to correct this issue.

**Comment by schwab** [comment]
Attempted to work around this by setting NEXTAUTH_URL=http://localhost:3002/, Note, this requires a restart.  When set correctly this way, a login was allowed. However, the graph list is empty and entering a graph name manually does not seem to work.  Entering any query then kicks you out to the login prompt again.

**Comment by gkorland** [comment]
Yes, it's like this in development mode. Due to the auto recompile it drops the in memory state of the server.
I didn't figure it out yet...
Are you working on the code or just want to use the browser? 
If you just want to use the browser run:

```
npm run build
npm run start
```
